// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameStudent = "students"

// Student 学生信息表
type Student struct {
	ID             int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:学生ID（主键）" json:"id"` // 学生ID（主键）
	Name           string         `gorm:"column:name;not null" json:"name"`
	Password       string         `gorm:"column:password;not null" json:"password"`
	Email          string         `gorm:"column:email;not null" json:"email"`
	LastLoginTime  *time.Time     `gorm:"column:last_login_time" json:"last_login_time"`
	Gender         *int32         `gorm:"column:gender;default:1" json:"gender"`
	Birthday       *time.Time     `gorm:"column:birthday" json:"birthday"`
	Phone          *string        `gorm:"column:phone" json:"phone"`
	ResumePath     *string        `gorm:"column:resume_path" json:"resume_path"`
	UniversityID   *int64         `gorm:"column:university_id" json:"university_id"`
	Major          *string        `gorm:"column:major" json:"major"`
	Education      *string        `gorm:"column:education;default:本科" json:"education"`
	GraduationYear *int64         `gorm:"column:graduation_year" json:"graduation_year"`
	Status         *string        `gorm:"column:status;default:在读" json:"status"`
	Remarks        *string        `gorm:"column:remarks" json:"remarks"`
	Avatar         *string        `gorm:"column:avatar" json:"avatar"`
	CreatedAt      *time.Time     `gorm:"column:created_at" json:"created_at"`
	UpdatedAt      *time.Time     `gorm:"column:updated_at" json:"updated_at"`
	CreatedBy      *int64         `gorm:"column:created_by" json:"created_by"`
	UpdatedBy      *int64         `gorm:"column:updated_by" json:"updated_by"`
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Student's table name
func (*Student) TableName() string {
	return TableNameStudent
}
