// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUniversity = "universities"

// University 大学信息表
type University struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:大学ID" json:"id"` // 大学ID
	Name      string         `gorm:"column:name;not null" json:"name"`
	CreatedAt *time.Time     `gorm:"column:created_at" json:"created_at"`
	UpdatedAt *time.Time     `gorm:"column:updated_at" json:"updated_at"`
	CreatedBy *int64         `gorm:"column:created_by" json:"created_by"`
	UpdatedBy *int64         `gorm:"column:updated_by" json:"updated_by"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName University's table name
func (*University) TableName() string {
	return TableNameUniversity
}
