// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User 用户表
type User struct {
	ID            int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:用户ID" json:"id"` // 用户ID
	Email         string         `gorm:"column:email;not null" json:"email"`
	Password      string         `gorm:"column:password;not null" json:"password"`
	Role          int32          `gorm:"column:role;not null;default:2" json:"role"`
	LastLoginTime *time.Time     `gorm:"column:last_login_time" json:"last_login_time"`
	Status        int32          `gorm:"column:status;not null;default:1" json:"status"`
	CreatedAt     *time.Time     `gorm:"column:created_at" json:"created_at"`
	UpdatedAt     *time.Time     `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Username      string         `gorm:"column:username;not null" json:"username"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
